<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210628191826 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_eav_type (DOCUMENT_EAV_TYPE_ID INT AUTO_INCREMENT NOT NULL, DOCUMENT_EAV_TYPE_CODE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_TYPE_TITLE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_TYPE_ORDER VARCHAR(255) DEFAULT NULL, PRIMARY KEY(DOCUMENT_EAV_TYPE_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE document_eav DROP FOREIGN KEY FK_A777ACD27671AC3F');
        $this->addSql('DROP INDEX FK_DOCUMENT_EAV_DOCUMENT_ENTITY ON document_eav');
        $this->addSql('ALTER TABLE document_eav CHANGE document_id DOCUMENT_EAV_TYPE_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_eav ADD CONSTRAINT FK_A777ACD24352B72F FOREIGN KEY (DOCUMENT_EAV_TYPE_ID) REFERENCES document_eav_type (DOCUMENT_EAV_TYPE_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_EAV_DOCUMENT_EAV_TYPE ON document_eav (DOCUMENT_EAV_TYPE_ID)');
        $this->addSql('ALTER TABLE document_entity_boolean DROP FOREIGN KEY FK_63054F47B082086C');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_BOOLEAN_DOCUMENT_EAV ON document_entity_boolean');
        $this->addSql('ALTER TABLE document_entity_boolean DROP DOCUMENT_EAV_CODE, DROP DOCUMENT_EAV_TITLE, DROP DOCUMENT_EAV_IS_VISIBLE, DROP DOCUMENT_EAV_DESCIPTION, DROP DOCUMENT_EAV_VALIDATION_RULE, CHANGE document_eav_id DOCUMENT_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_boolean ADD CONSTRAINT FK_63054F477671AC3F FOREIGN KEY (DOCUMENT_ID) REFERENCES document_entity (DOCUMENT_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_BOOLEAN_DOCUMENT_ENTITY ON document_entity_boolean (DOCUMENT_ID)');
        $this->addSql('ALTER TABLE document_entity_date DROP FOREIGN KEY FK_60FBB93BB082086C');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_DATE_DOCUMENT_EAV ON document_entity_date');
        $this->addSql('ALTER TABLE document_entity_date DROP DOCUMENT_EAV_CODE, DROP DOCUMENT_EAV_TITLE, DROP DOCUMENT_EAV_IS_VISIBLE, DROP DOCUMENT_EAV_DESCIPTION, DROP DOCUMENT_EAV_VALIDATION_RULE, CHANGE document_eav_id DOCUMENT_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_date ADD CONSTRAINT FK_60FBB93B7671AC3F FOREIGN KEY (DOCUMENT_ID) REFERENCES document_entity (DOCUMENT_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_DATE_DOCUMENT_ENTITY ON document_entity_date (DOCUMENT_ID)');
        $this->addSql('ALTER TABLE document_entity_int DROP FOREIGN KEY FK_CB1D1140B082086C');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_INT_DOCUMENT_EAV ON document_entity_int');
        $this->addSql('ALTER TABLE document_entity_int DROP DOCUMENT_EAV_CODE, DROP DOCUMENT_EAV_TITLE, DROP DOCUMENT_EAV_IS_VISIBLE, DROP DOCUMENT_EAV_DESCIPTION, DROP DOCUMENT_EAV_VALIDATION_RULE, CHANGE document_eav_id DOCUMENT_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_int ADD CONSTRAINT FK_CB1D11407671AC3F FOREIGN KEY (DOCUMENT_ID) REFERENCES document_entity (DOCUMENT_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_INT_DOCUMENT_ENTITY ON document_entity_int (DOCUMENT_ID)');
        $this->addSql('ALTER TABLE document_entity_varchar DROP FOREIGN KEY FK_16541A93B082086C');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_VARCHAR_DOCUMENT_EAV ON document_entity_varchar');
        $this->addSql('ALTER TABLE document_entity_varchar DROP DOCUMENT_EAV_CODE, DROP DOCUMENT_EAV_TITLE, DROP DOCUMENT_EAV_IS_VISIBLE, DROP DOCUMENT_EAV_DESCIPTION, DROP DOCUMENT_EAV_VALIDATION_RULE, CHANGE document_eav_id DOCUMENT_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_varchar ADD CONSTRAINT FK_16541A937671AC3F FOREIGN KEY (DOCUMENT_ID) REFERENCES document_entity (DOCUMENT_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_VARCHAR_DOCUMENT_ENTITY ON document_entity_varchar (DOCUMENT_ID)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document_eav DROP FOREIGN KEY FK_A777ACD24352B72F');
        $this->addSql('DROP TABLE document_eav_type');
        $this->addSql('DROP INDEX FK_DOCUMENT_EAV_DOCUMENT_EAV_TYPE ON document_eav');
        $this->addSql('ALTER TABLE document_eav CHANGE document_eav_type_id DOCUMENT_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_eav ADD CONSTRAINT FK_A777ACD27671AC3F FOREIGN KEY (DOCUMENT_ID) REFERENCES document_entity (DOCUMENT_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_EAV_DOCUMENT_ENTITY ON document_eav (DOCUMENT_ID)');
        $this->addSql('ALTER TABLE document_entity_boolean DROP FOREIGN KEY FK_63054F477671AC3F');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_BOOLEAN_DOCUMENT_ENTITY ON document_entity_boolean');
        $this->addSql('ALTER TABLE document_entity_boolean ADD DOCUMENT_EAV_CODE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_TITLE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, ADD DOCUMENT_EAV_DESCIPTION TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_VALIDATION_RULE TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE document_id DOCUMENT_EAV_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_boolean ADD CONSTRAINT FK_63054F47B082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_BOOLEAN_DOCUMENT_EAV ON document_entity_boolean (DOCUMENT_EAV_ID)');
        $this->addSql('ALTER TABLE document_entity_date DROP FOREIGN KEY FK_60FBB93B7671AC3F');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_DATE_DOCUMENT_ENTITY ON document_entity_date');
        $this->addSql('ALTER TABLE document_entity_date ADD DOCUMENT_EAV_CODE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_TITLE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, ADD DOCUMENT_EAV_DESCIPTION TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_VALIDATION_RULE TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE document_id DOCUMENT_EAV_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_date ADD CONSTRAINT FK_60FBB93BB082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_DATE_DOCUMENT_EAV ON document_entity_date (DOCUMENT_EAV_ID)');
        $this->addSql('ALTER TABLE document_entity_int DROP FOREIGN KEY FK_CB1D11407671AC3F');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_INT_DOCUMENT_ENTITY ON document_entity_int');
        $this->addSql('ALTER TABLE document_entity_int ADD DOCUMENT_EAV_CODE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_TITLE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, ADD DOCUMENT_EAV_DESCIPTION TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_VALIDATION_RULE TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE document_id DOCUMENT_EAV_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_int ADD CONSTRAINT FK_CB1D1140B082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_INT_DOCUMENT_EAV ON document_entity_int (DOCUMENT_EAV_ID)');
        $this->addSql('ALTER TABLE document_entity_varchar DROP FOREIGN KEY FK_16541A937671AC3F');
        $this->addSql('DROP INDEX FK_DOCUMENT_ENTITY_VARCHAR_DOCUMENT_ENTITY ON document_entity_varchar');
        $this->addSql('ALTER TABLE document_entity_varchar ADD DOCUMENT_EAV_CODE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_TITLE VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, ADD DOCUMENT_EAV_DESCIPTION TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ADD DOCUMENT_EAV_VALIDATION_RULE TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE document_id DOCUMENT_EAV_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_entity_varchar ADD CONSTRAINT FK_16541A93B082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('CREATE INDEX FK_DOCUMENT_ENTITY_VARCHAR_DOCUMENT_EAV ON document_entity_varchar (DOCUMENT_EAV_ID)');
    }
}
