<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210429164304 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE customer (CUSTOMER_ID INT AUTO_INCREMENT NOT NULL, CUSTOMER_COMPANY VARCHAR(200) DEFAULT NULL, CUSTOMER_ADDRESS VARCHAR(200) DEFAULT NULL, CUSTOMER_CITY VARCHAR(100) DEFAULT NULL, CUSTOMER_POSTAL_CODE VARCHAR(5) DEFAULT NULL, CUSTOMER_CONTACT_NAME VARCHAR(100) DEFAULT NULL, CUSTOMER_DIRECTION VARCHAR(150) DEFAULT NULL, PRIMARY KEY(CUSTOMER_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_eav (DOCUMENT_EAV_ID INT AUTO_INCREMENT NOT NULL, DOCUMENT_EAV_CODE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_TITLE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, DOCUMENT_EAV_DESCIPTION TEXT DEFAULT NULL, DOCUMENT_EAV_VALIDATION_RULE TEXT DEFAULT NULL, DOCUMENT_ID INT DEFAULT NULL, INDEX FK_DOCUMENT_EAV_DOCUMENT_ENTITY (DOCUMENT_ID), PRIMARY KEY(DOCUMENT_EAV_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_entity (DOCUMENT_ID INT AUTO_INCREMENT NOT NULL, DOCUMENT_REFERENCE VARCHAR(50) DEFAULT NULL, DOCUMENT_CREATED_AT DATE DEFAULT NULL, DOCTYPE_ID INT DEFAULT NULL, EMPLOYEE_ID INT DEFAULT NULL, SITE_ID INT DEFAULT NULL, INDEX FK_DOCUMENT_ENTITY_DOCUMENT_TYPE (DOCTYPE_ID), INDEX FK_DOCUMENT_ENTITY_SITE (SITE_ID), INDEX FK_DOCUMENT_ENTITY_EMPLOYEE (EMPLOYEE_ID), PRIMARY KEY(DOCUMENT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_entity_boolean (DOCUMENT_ENTITY_BOOLEAN_ID INT AUTO_INCREMENT NOT NULL, DOCUMENT_ENTITY_BOOLEAN_VALUE TINYINT(1) DEFAULT NULL, DOCUMENT_EAV_CODE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_TITLE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, DOCUMENT_EAV_DESCIPTION TEXT DEFAULT NULL, DOCUMENT_EAV_VALIDATION_RULE TEXT DEFAULT NULL, DOCUMENT_EAV_ID INT DEFAULT NULL, INDEX FK_DOCUMENT_ENTITY_BOOLEAN_DOCUMENT_EAV (DOCUMENT_EAV_ID), PRIMARY KEY(DOCUMENT_ENTITY_BOOLEAN_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_entity_date (DOCUMENT_ENTITY_DATE_ID INT AUTO_INCREMENT NOT NULL, DOCUMENT_ENTITY_DATE_VALUE DATE DEFAULT NULL, DOCUMENT_EAV_CODE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_TITLE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, DOCUMENT_EAV_DESCIPTION TEXT DEFAULT NULL, DOCUMENT_EAV_VALIDATION_RULE TEXT DEFAULT NULL, DOCUMENT_EAV_ID INT DEFAULT NULL, INDEX FK_DOCUMENT_ENTITY_DATE_DOCUMENT_EAV (DOCUMENT_EAV_ID), PRIMARY KEY(DOCUMENT_ENTITY_DATE_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_entity_int (DOCUMENT_ENTITY_INT_ID INT AUTO_INCREMENT NOT NULL, DOCUMENT_ENTITY_INT_VALUE INT DEFAULT NULL, DOCUMENT_EAV_CODE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_TITLE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, DOCUMENT_EAV_DESCIPTION TEXT DEFAULT NULL, DOCUMENT_EAV_VALIDATION_RULE TEXT DEFAULT NULL, DOCUMENT_EAV_ID INT DEFAULT NULL, INDEX FK_DOCUMENT_ENTITY_INT_DOCUMENT_EAV (DOCUMENT_EAV_ID), PRIMARY KEY(DOCUMENT_ENTITY_INT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_entity_varchar (DOCUMENT_ENTITY_VARCHAR_ID INT AUTO_INCREMENT NOT NULL, DOCUMENT_ENTITY_VARCHAR_VALUE TEXT DEFAULT NULL, DOCUMENT_EAV_CODE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_TITLE VARCHAR(255) DEFAULT NULL, DOCUMENT_EAV_IS_VISIBLE TINYINT(1) DEFAULT NULL, DOCUMENT_EAV_DESCIPTION TEXT DEFAULT NULL, DOCUMENT_EAV_VALIDATION_RULE TEXT DEFAULT NULL, DOCUMENT_EAV_ID INT DEFAULT NULL, INDEX FK_DOCUMENT_ENTITY_VARCHAR_DOCUMENT_EAV (DOCUMENT_EAV_ID), PRIMARY KEY(DOCUMENT_ENTITY_VARCHAR_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_type (DOCTYPE_ID INT AUTO_INCREMENT NOT NULL, DOCTYPE_TITLE VARCHAR(150) DEFAULT NULL, PRIMARY KEY(DOCTYPE_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE employee (EMPLOYEE_ID INT AUTO_INCREMENT NOT NULL, EMPLOYEE_FIRSTNAME VARCHAR(50) DEFAULT NULL, EMPLOYEE_LASTNAME VARCHAR(50) DEFAULT NULL, EMPLOYEE_EMAIL VARCHAR(200) DEFAULT NULL, EMPLOYEE_ADDRESS VARCHAR(300) DEFAULT NULL, EMPLOYEE_CITY VARCHAR(100) DEFAULT NULL, EMPLOYEE_POSTAL_CODE VARCHAR(5) DEFAULT NULL, EMPLOYEE_HASHED_MDP VARCHAR(32) DEFAULT NULL, EMPLOYEE_GENRE TINYINT(1) DEFAULT NULL, EMPLOYEE_CREATED_AT VARCHAR(32) DEFAULT NULL, roles JSON NOT NULL, ROLE_ID INT DEFAULT NULL, UNIQUE INDEX UNIQ_5D9F75A1E31B0E06 (EMPLOYEE_EMAIL), INDEX FK_EMPLOYEE_ROLE (ROLE_ID), PRIMARY KEY(EMPLOYEE_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (PRODUCT_ID INT AUTO_INCREMENT NOT NULL, PRODUCT_TITLE VARCHAR(200) DEFAULT NULL, PRODUCT_UNITARY_PRICE NUMERIC(10, 2) DEFAULT NULL, PRODUCT_DIMENSION VARCHAR(200) DEFAULT NULL, PRIMARY KEY(PRODUCT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE provider (PROVIDER_ID INT AUTO_INCREMENT NOT NULL, PROVIDER_COMPANY_NAME VARCHAR(150) DEFAULT NULL, PROVIDER_SIRET VARCHAR(50) DEFAULT NULL, PROVIDER_CONTACT_FULLNAME VARCHAR(150) DEFAULT NULL, PROVIDER_CONTACT_GENRE TINYINT(1) DEFAULT NULL, PROVIDER_EMAIL VARCHAR(150) DEFAULT NULL, PROVIDER_TEL VARCHAR(10) DEFAULT NULL, PRIMARY KEY(PROVIDER_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_order (PURCH_ORDER_ID INT AUTO_INCREMENT NOT NULL, PURCH_ORDER_CREATED_AT DATE DEFAULT NULL, PURCH_ORDER_ASKED_PRICE NUMERIC(10, 2) DEFAULT NULL, PURCH_ORDER_DELIVERY_DATE DATE DEFAULT NULL, PURCH_ORDER_DELIVERY_LOCATION VARCHAR(200) DEFAULT NULL, PURCH_ORDER_NB_PAGE INT DEFAULT NULL, EMPLOYEE_ID INT DEFAULT NULL, PROVIDER_ID INT DEFAULT NULL, INDEX FK_PURCHASE_ORDER_PROVIDER (PROVIDER_ID), INDEX FK_PURCHASE_ORDER_EMPLOYEE (EMPLOYEE_ID), PRIMARY KEY(PURCH_ORDER_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_order_product (QUANTITY INT NOT NULL, PURCH_ORDER_ID INT NOT NULL, PRODUCT_ID INT NOT NULL, INDEX IDX_F32214F94BBA2C4B (PURCH_ORDER_ID), INDEX IDX_F32214F976563D85 (PRODUCT_ID), PRIMARY KEY(PURCH_ORDER_ID, PRODUCT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password (RESET_PSWD_ID INT AUTO_INCREMENT NOT NULL, RESET_PSWD_CODE VARCHAR(32) DEFAULT NULL, RESET_PSWD_STATUS TINYINT(1) DEFAULT NULL, RESET_PSWD_CREATED_AT DATE DEFAULT NULL, EMPLOYEE_ID INT DEFAULT NULL, INDEX FK_RESET_PASSWORD_EMPLOYEE (EMPLOYEE_ID), PRIMARY KEY(RESET_PSWD_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (ROLE_ID INT AUTO_INCREMENT NOT NULL, ROLE_TITLE VARCHAR(32) DEFAULT NULL, PRIMARY KEY(ROLE_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE site (SITE_ID INT AUTO_INCREMENT NOT NULL, SITE_TITLE VARCHAR(200) DEFAULT NULL, SITE_CREATED_AT DATE DEFAULT NULL, CUSTOMER_ID INT DEFAULT NULL, INDEX FK_SITE_CUSTOMER (CUSTOMER_ID), PRIMARY KEY(SITE_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE document_eav ADD CONSTRAINT FK_A777ACD27671AC3F FOREIGN KEY (DOCUMENT_ID) REFERENCES document_entity (DOCUMENT_ID)');
        $this->addSql('ALTER TABLE document_entity ADD CONSTRAINT FK_B04AF50E8DCA2D63 FOREIGN KEY (DOCTYPE_ID) REFERENCES document_type (DOCTYPE_ID)');
        $this->addSql('ALTER TABLE document_entity ADD CONSTRAINT FK_B04AF50E394D2554 FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee (EMPLOYEE_ID)');
        $this->addSql('ALTER TABLE document_entity ADD CONSTRAINT FK_B04AF50EF1B5AEBC FOREIGN KEY (SITE_ID) REFERENCES site (SITE_ID)');
        $this->addSql('ALTER TABLE document_entity_boolean ADD CONSTRAINT FK_63054F47B082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('ALTER TABLE document_entity_date ADD CONSTRAINT FK_60FBB93BB082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('ALTER TABLE document_entity_int ADD CONSTRAINT FK_CB1D1140B082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('ALTER TABLE document_entity_varchar ADD CONSTRAINT FK_16541A93B082086C FOREIGN KEY (DOCUMENT_EAV_ID) REFERENCES document_eav (DOCUMENT_EAV_ID)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1D10B9A56 FOREIGN KEY (ROLE_ID) REFERENCES role (ROLE_ID)');
        $this->addSql('ALTER TABLE purchase_order ADD CONSTRAINT FK_21E210B2394D2554 FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee (EMPLOYEE_ID)');
        $this->addSql('ALTER TABLE purchase_order ADD CONSTRAINT FK_21E210B2BF1D7CA2 FOREIGN KEY (PROVIDER_ID) REFERENCES provider (PROVIDER_ID)');
        $this->addSql('ALTER TABLE purchase_order_product ADD CONSTRAINT FK_F32214F94BBA2C4B FOREIGN KEY (PURCH_ORDER_ID) REFERENCES purchase_order (PURCH_ORDER_ID)');
        $this->addSql('ALTER TABLE purchase_order_product ADD CONSTRAINT FK_F32214F976563D85 FOREIGN KEY (PRODUCT_ID) REFERENCES product (PRODUCT_ID)');
        $this->addSql('ALTER TABLE reset_password ADD CONSTRAINT FK_B9983CE5394D2554 FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee (EMPLOYEE_ID)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E426DB17FB FOREIGN KEY (CUSTOMER_ID) REFERENCES customer (CUSTOMER_ID)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E426DB17FB');
        $this->addSql('ALTER TABLE document_entity_boolean DROP FOREIGN KEY FK_63054F47B082086C');
        $this->addSql('ALTER TABLE document_entity_date DROP FOREIGN KEY FK_60FBB93BB082086C');
        $this->addSql('ALTER TABLE document_entity_int DROP FOREIGN KEY FK_CB1D1140B082086C');
        $this->addSql('ALTER TABLE document_entity_varchar DROP FOREIGN KEY FK_16541A93B082086C');
        $this->addSql('ALTER TABLE document_eav DROP FOREIGN KEY FK_A777ACD27671AC3F');
        $this->addSql('ALTER TABLE document_entity DROP FOREIGN KEY FK_B04AF50E8DCA2D63');
        $this->addSql('ALTER TABLE document_entity DROP FOREIGN KEY FK_B04AF50E394D2554');
        $this->addSql('ALTER TABLE purchase_order DROP FOREIGN KEY FK_21E210B2394D2554');
        $this->addSql('ALTER TABLE reset_password DROP FOREIGN KEY FK_B9983CE5394D2554');
        $this->addSql('ALTER TABLE purchase_order_product DROP FOREIGN KEY FK_F32214F976563D85');
        $this->addSql('ALTER TABLE purchase_order DROP FOREIGN KEY FK_21E210B2BF1D7CA2');
        $this->addSql('ALTER TABLE purchase_order_product DROP FOREIGN KEY FK_F32214F94BBA2C4B');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A1D10B9A56');
        $this->addSql('ALTER TABLE document_entity DROP FOREIGN KEY FK_B04AF50EF1B5AEBC');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE document_eav');
        $this->addSql('DROP TABLE document_entity');
        $this->addSql('DROP TABLE document_entity_boolean');
        $this->addSql('DROP TABLE document_entity_date');
        $this->addSql('DROP TABLE document_entity_int');
        $this->addSql('DROP TABLE document_entity_varchar');
        $this->addSql('DROP TABLE document_type');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE provider');
        $this->addSql('DROP TABLE purchase_order');
        $this->addSql('DROP TABLE purchase_order_product');
        $this->addSql('DROP TABLE reset_password');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE site');
    }
}
