version: '3'

networks:
  dev:

volumes:
  db-data:

services:
  db:
    image: mysql
    container_name: db_docker_symfony
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=plafitech_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
    networks:
      - dev

  app:
    image: m0nar0/symfony_docker
    ports:
      - 8080:80
    networks:
      - dev